### ISSUE TITLE
Unify as MIT License

### ISSUE THREAD

**Issue by jserv** [rswinkle/PortableGL#10]
Recently, [TinyGL](https://bellard.org/TinyGL/)  was relicensed to MIT, which implies that file [LICENSE](https://github.com/rswinkle/PortableGL/blob/master/LICENSE) can be unified as single MIT License. That is,
> The MIT License (MIT)
> Copyright (c) 2011-2022 Robert Winkler
> Copyright (c) 1997-1998 Fabrice Bellard

Reference: https://bellard.org/TinyGL/changelog.html

**Comment by rswinkle** [comment]
Thanks I wouldn't have found out about that for ages.  Now I can't decide how I want to put it in the LICENSE file and the header_docs.txt

And technically his LICENSE now says 1997-2022 even though the clipping code I'm using probably has been unchanged since 1998.

I'm leaning toward something like what you have

> The MIT License (MIT)
> Copyright (c) 2011-2022 Robert Winkler
> Copyright (c) 1997-1998 Fabrice Bellard (clipping code from TinyGL)

Maybe I'm supposed to go to 2022 just because that's when he changed the license?
