### ISSUE TITLE
Need help in implementing in game.

### ISSUE THREAD

**Issue by arczi84** [rswinkle/PortableGL#16]
Hello, congrats on this a cool project.
I would like to implement PortableGL in WipeOut 1 https://github.com/phoboslab/wipeout-rewrite
I have got game running, most gl function except anisotropy options links with PGL.

Added new renderer based on SOFTWARE and GL ones in platform_sdl.c :

```
#elif defined(RENDERER_PORTABLEGL) // ----------------------------------------------
	#define PLATFORM_WINDOW_FLAGS 0

	#define HEIGHT SYSTEM_WINDOW_HEIGHT
	#define WIDTH SYSTEM_WINDOW_WIDTH 
	static SDL_Texture *screenbuffer = NULL;
	static void *screenbuffer_pixels = NULL;
	static int screenbuffer_pitch;
	static vec2i_t screenbuffer_size = vec2i(0, 0);
	static vec2i_t screen_size = vec2i(0, 0);


	void platform_video_init(void) {
		SDL_GLContext platform_gl;
		platform_gl = SDL_GL_CreateContext(window);

		SDL_GL_SetSwapInterval(1);

		SDL_SetMainReady();
		renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_SOFTWARE);
		if (!init_glContext(&the_context, &bbufpix, WIDTH, HEIGHT, 32, 0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000)) {
				puts("Failed to initialize glContext");
				exit(0);
			}
	}

	void platform_video_cleanup() {
		if (screenbuffer) {
			SDL_DestroyTexture(screenbuffer);
		}
		SDL_DestroyRenderer(renderer);
		free_glContext(&the_context);
	}

	void platform_prepare_frame() {
		SDL_GL_SwapWindow(window); //??
		if (screen_size.x != screenbuffer_size.x || screen_size.y != screenbuffer_size.y) {
			if (screenbuffer) {
				SDL_DestroyTexture(screenbuffer);
			}
			screenbuffer = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_ABGR8888, SDL_TEXTUREACCESS_STREAMING, WIDTH, HEIGHT);
			screenbuffer_size = screen_size;

		}
		SDL_LockTexture(screenbuffer, NULL, &screenbuffer_pixels, &screenbuffer_pitch);
	}

	void platform_end_frame() {
		screenbuffer_pixels = NULL;
		SDL_UnlockTexture(screenbuffer);
		SDL_UpdateTexture(screenbuffer, NULL, bbufpix, WIDTH * sizeof(uint32_t));
		SDL_RenderCopy(renderer, screenbuffer, NULL, NULL);
		SDL_RenderPresent(renderer);
	}

	rgba_t *platform_get_screenbuffer(int32_t *pitch) {
		*pitch = screenbuffer_pitch;
		return screenbuffer_pixels;
	}

	vec2i_t platform_screen_size() {
		int width, height;
		SDL_GetWindowSize(window, &width, &height);

			screen_size = vec2i(width, height);
		return screen_size;
	}

```

and in render_gl.c  commented out glewInit(); and replaced glCreateProgram() : 

```
	//GLuint program = glCreateProgram();
	GLenum flat = PGL_FLAT; 
	GLuint program = pglCreateProgram(vs, fs, 1, &flat, GL_FALSE);
```

End result is just blue flashing rectangle. 
![obraz](https://github.com/rswinkle/PortableGL/assets/3505526/40d89ec0-0cbe-4265-b184-cc0d3e9b33c8)

Any help would be appreciated.

**Comment by rswinkle** [comment]
I am so sorry I never responded to this.  I just checked and I can't find any email notification that I missed unless it got sent to spam and is already gone because it is over 30 days old.  Obviously I haven't been really active in this project since last November and thought I already had 3 issues even back then so never realized when I glanced at it.

You shouldn't be using any of SDL's GL functions.  PGL is *not* a "real" OpenGL and it doesn't need SDL to create a context.  It creates its own "context".  Look at the PGL examples/demos for how it works with SDL2 or the documentation at the top of portablegl.h for a general overview.

I am curious.  The repo you link to uses SDL2 but the fork on your profile uses SDL1.2?  Why go backward like that?  Even SDL2 is technically deprecated for new projects since they've been working on SDL3 for over a year now.  Plus all of PortableGL's examples use SDL2 so there might be subtle differences if you're trying to apply what you see there to SDL1.2.

**Comment by rswinkle** [comment]
PPS. You should really be basing your backend on the already existing RENDERER_SOFTWARE backend.  Though I would change a few things about how it does it because PGL already has its own back buffer and there's no need to lock the pixels.  Also it makes more sense to create a new SDL Texture in the input handling when you have a window resize event rather than checking every single frame if the sizes match.

**Comment by arczi84** [comment]
> I am so sorry I never responded to this. I just checked and I can't find any email notification that I missed unless it got sent to spam and is already gone because it is over 30 days old. Obviously I haven't been really active in this project since last November and thought I already had 3 issues even back then so never realized when I glanced at it.
> 

Thanks for answer anyway. 

> You shouldn't be using any of SDL's GL functions. PGL is _not_ a "real" OpenGL and it doesn't need SDL to create a context. It creates its own "context". Look at the PGL examples/demos for how it works with SDL2 or the documentation at the top of portablegl.h for a general overview.
> 

I tried with and without SDL GL functions with the same result.

> I am curious. The repo you link to uses SDL2 but the fork on your profile uses SDL1.2? Why go backward like that? Even SDL2 is technically deprecated for new projects since they've been working on SDL3 for over a year now. Plus all of PortableGL's examples use SDL2 so there might be subtle differences if you're trying to apply what you see there to SDL1.2.
>

I have created SDL1.2 fork as my target platform (Amiga) only has SDL1.2.  My compiled example works with it.
For testing PGL in WipeOut I use SDL2.

> PS. In general adding PGL as a software rendering backend will require more work than just dropping it in and expecting it to fit in with other OpenGL backends with minimal changes. 
>

It looked simple with examples at least :) But if that requires more work than I have not enough experience with OpenGL.

>
You will have to, at the very least, port the shaders to C/C++ and account for differences like that in your abstraction over rendering backends.
>

I don't understand. Both codes are in C?

Maybe this shader code isn't compatible with pgl?

`
	GLuint vs = compile_shader(GL_VERTEX_SHADER, vs_source);
	GLuint fs = compile_shader(GL_FRAGMENT_SHADER, fs_source);
	
	//GLuint program = glCreateProgram();
	GLenum flat = PGL_FLAT; 
	GLuint program = pglCreateProgram(vs, fs, 1, &flat, GL_FALSE);


static GLuint compile_shader(GLenum type, const char *source) {
	GLuint shader = glCreateShader(type);
	glShaderSource(shader, 1, &source, NULL);
	glCompileShader(shader);
	
	GLint success;
	glGetShaderiv(shader, GL_COMPILE_STATUS, &success);
	if (!success) {
		int log_written;
		char log[256];
		glGetShaderInfoLog(shader, 256, &log_written, log);
		die("Error compiling shader: %s\n", log);
	}
	return shader;
}
`

>
PPS. You should really be basing your backend on the already existing RENDERER_SOFTWARE backend.
>

I mixed both renderers Original software renderer only displays wireframes so for fully textured render I need also GL backend texture loading code.

**Comment by rswinkle** [comment]
>I tried with and without SDL GL functions with the same result.

I would have to see what you actually tried to figure out what was going on, but I've also never used PGL with 1.2 so I'd have to see that too.  It might be worth getting it working with SDL 2 first based on the repo you forked off of before going straight to 1.2 just because that's what all the examples use.

> I have created SDL1.2 fork as my target platform (Amiga) only has SDL1.2. My compiled example works with it.
For testing PGL in WipeOut I use SDL2.

Is this for an actual Amiga or an Amiga emulator?  I'm assuming the latter, but that would be really cool if SDL 1.2 supported real Amigas.

>It looked simple with examples at least :) But if that requires more work than I have not enough experience with OpenGL.
>I don't understand. Both codes are in C?
>Maybe this shader code isn't compatible with pgl?

PGL does not use real shaders.  To simplify the implementation, shaders are written in C/C++ so the API surrounding them is different than real OpenGL.

Look at the difference between [this real OpenGL program](https://github.com/rswinkle/opengl_reference/blob/master/src/ex1.c) and the equivalent [PGL program](https://github.com/rswinkle/PortableGL/blob/master/examples/ex1.c).  You can also look at the documentation/example at the top of [portablegl.h](https://github.com/rswinkle/PortableGL/blob/master/portablegl.h#L63)

The differences also include how uniforms are handled and how you specify the varying of vertex attributes (the latter is based on a parameter to pglCreateProgram()).

Long story short, all the code in compile_shader() does not do anything for PGL.  If it compiles at all, it's only because I've added a bunch of stub functions to help with porting.   Whatever the shaders are in those strings you're compiling there, you'd have to rewrite as 2 C functions and those become the first and second parameters to pglCreateProgram.

>I mixed both renderers Original software renderer only displays wireframes so for fully textured render I need also GL backend texture loading code.

I didn't mean using all of it just that section between the ifdef as a model to create your new section because PGL is also a software renderer.  So you would combine basically that with most of the main code for the normal codes just with the PGL specific changes (ie shaders and uniforms etc.).

I think you're probably right that this is more complicated and more work that you were expecting and I'm sorry that's the case.  You can look at some alternatives listed in the README but getting any of them integrated and working will be a bit of a pain, though it varies on exactly what kind of pain.  For PGL the pain is in the porting, not the integration/building.  For something like Mesa, it might work with minimal changes, but adding it to the build/project is not as simple as just dropping a single h file into the project like with PGL.
