### ISSUE TITLE
RGBA8888 Byte Format

### ISSUE THREAD

**Issue by RobLoach** [rswinkle/PortableGL#17]
This is such an awesome project! Have OpenGL-esque API in software rendering opens up portability to embedded systems, which is huge.

I've put together a small software-rendering library which facilitates a number of different platforms. While using PortableGL in [raylib](https://www.raylib.com/), which uses an `RGBA8888` pixel format, it ends up rendering like....

![Screenshot from 2024-04-17 14-49-38](https://github.com/rswinkle/PortableGL/assets/25086/c3b51d3b-8962-44bd-80ad-06added7e023)

While I have been able to switch up the masks, I'm unsure why the alpha looks to be weird.

``` c
#ifdef PNTR_PIXELFORMAT_RGBA
    // TODO: raylib: Fix alpha mask
    u32 Rmask = 0x000000FF;
    u32 Gmask = 0x0000FF00;
    u32 Bmask = 0x00FF0000;
    u32 Amask = 0xFF000000;
#elif defined(PNTR_PIXELFORMAT_ARGB)
    #if defined(SDL_BYTEORDER) && SDL_BYTEORDER == SDL_BIG_ENDIAN
        u32 Rmask = 0xFF000000;
        u32 Gmask = 0x00FF0000;
        u32 Bmask = 0x0000FF00;
        u32 Amask = 0x000000FF;
    #else
        u32 Rmask = 0x00FF0000;
        u32 Gmask = 0x0000FF00;
        u32 Bmask = 0x000000FF;
        u32 Amask = 0xFF000000;
    #endif
#endif
```
https://github.com/RobLoach/pntr_portablegl/blob/master/examples/ex2.c

Would you happen to know what would be wrong? It works perfectly in SDL with ARGB

**Comment by rswinkle** [comment]
Sorry for the delay in reply, it turns out I'm not watching my own (most popular) repo and haven't been getting any emails for it.  Hopefully that's fixed now.

I just cloned and compiled on my side and yeah, that is definitely weird.  I'll look into it right now.

I do have a few questions.  If I'm understanding this right, with raylib, you're just using PGL as an offscreen texture generator and then using raylib to put that on screen?  Because it says Raylib is still using GLFW which is real OpenGL only.  I know Raylib 5 does support SDL as a backend which is why one of my long term goals is to create a proper PGL backend to raylib integrated with rlgl.h.

A few minutes later...

I know I might be biased but I don't think it's a problem with PGL or your color mask specification.  Just as a sanity check I just tried changing that same example to use RGBA8888 in the PGL repo and it worked perfectly.  Mismatching the SDL texture description and the PGL masks ended with as expected mixed up colors.

My best guess is that it's something happening between pntr and real OpenGL.  I would say it's something to do with how you're sending the data to OpenGL or the OpenGL blend settings, except .... what's with the gradient?  All of my ideas of what could be wrong would be uniformly off.

Any new ideas on your end?

**Comment by RobLoach** [comment]
> Sorry for the delay in reply, it turns out I'm not watching my own (most popular) repo and haven't been getting any emails for it.

No worries on response time. I know everyone gets busy. There's absolutely no urgency in any of this. I'm mostly exploring PortableGL to see if I could make some OpenGL-dependent libretro cores software rendered via PortableGL. 

>  If I'm understanding this right, with raylib, you're just using PGL as an offscreen texture generator and then using raylib to put that on screen?

Correct. The backbuffer is raw pixel data, and a raylib Texture is generated from it, and updated each frame. A similar approach is taken with SDL. For PGL, it's set up to rendering directly to that backbuffer with `user_allocated_backbuf` and `back`.

>  Just as a sanity check I just tried changing that same example to use RGBA8888 in the PGL repo

Was that with the following? https://github.com/rswinkle/PortableGL/blob/master/examples/ex2.cpp#L156C2-L156C101
```
tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_STREAMING, WIDTH, HEIGHT);

if (!init_glContext(&the_Context, &bbufpix, WIDTH, HEIGHT, 32, 0x000000FF, 0x0000FF00, 0x00FF0000, 0xFF000000)) {
  puts("Failed to initialize glContext");
  exit(0);
}
```

> My best guess is that it's something happening between pntr and real OpenGL. I would say it's something to do with how you're sending the data to OpenGL or the OpenGL blend settings, except .... what's with the gradient? All of my ideas of what could be wrong would be uniformly off.

Right? It's very strange. I just added a few rectangles at the top using software rendering via pntr to ensure the raylib textures are represented correctly...

``` c
    // Draw the triangle
    glClear(GL_COLOR_BUFFER_BIT);
    glDrawArrays(GL_TRIANGLES, 0, 3);

    pntr_draw_rectangle_fill(screen, 50, 50, 50, 50, pntr_new_color(255, 0, 0, 255));
    pntr_draw_rectangle_fill(screen, 100, 50, 50, 50, pntr_new_color(0, 255, 0, 255));
    pntr_draw_rectangle_fill(screen, 50, 100, 50, 50, pntr_new_color(0, 0, 255, 255));
```

### SDL

![Screenshot from 2024-04-21 17-54-49](https://github.com/rswinkle/PortableGL/assets/25086/f5310a98-e836-45c7-b260-b5925edcdfb2)

### raylib

![Screenshot from 2024-04-21 17-55-28](https://github.com/rswinkle/PortableGL/assets/25086/fc5c4f47-8809-425a-a4fb-35b407866483)

**Comment by rswinkle** [comment]
> No worries on response time. I know everyone gets busy. There's absolutely no urgency in any of this. I'm mostly exploring PortableGL to see if I could make some OpenGL-dependent libretro cores software rendered via PortableGL.

That would be awesome... I really need to get on this and tag 0.98.0 and get some momentum going again.  And be more proactive about getting funding/sponsorship to get to 1.0.  So many ideas, so little time/motivation when it doesn't pay the bills but takes large amounts of time/focus.  Instead I start new projects and experiments because that's simpler and more fun than the TODO list for PGL or any mature project.
 

> Was that with the following? https://github.com/rswinkle/PortableGL/blob/master/examples/ex2.cpp#L156C2-L156C101
> 
> ```c
> tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_STREAMING, WIDTH, HEIGHT);
> 
> if (!init_glContext(&the_Context, &bbufpix, WIDTH, HEIGHT, 32, 0x000000FF, 0x0000FF00, 0x00FF0000, 0xFF000000)) {
>   puts("Failed to initialize glContext");
>   exit(0);
> }
> ```
No actually, and I think this *might* be part of the problem but it still doesn't explain the gradient issue.  It actually looks like this
```c
//tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_ARGB8888, SDL_TEXTUREACCESS_STREAMING, WIDTH, HEIGHT);
tex = SDL_CreateTexture(ren, SDL_PIXELFORMAT_RGBA8888, SDL_TEXTUREACCESS_STREAMING, WIDTH, HEIGHT);

//if (!init_glContext(&the_Context, &bbufpix, WIDTH, HEIGHT, 32, 0x00FF0000, 0x0000FF00, 0x000000FF, 0xFF000000)) {
if (!init_glContext(&the_Context, &bbufpix, WIDTH, HEIGHT, 32, 0xFF000000, 0x00FF0000, 0x0000FF00, 0x000000FF)) {
```

So there are a couple of differences/inconsistencies/misunderstandings I noticed.

PGL uses the masks on the color as a u32, it is *not* used to express the order of the channels in memory directly.  This is also how SDL Pixel formats work as you can see above: in both ARGB and RGBA it is specified as if it's an MSB number (because endianess doesn't matter when viewed as a number rather than poking at the channels directly.

I also noticed this in pntr:
```c
    struct pntr_color_rgba_t {
        #if defined(PNTR_PIXELFORMAT_RGBA)
            /**
             * Red channel.
             */
            unsigned char r;

            /**
             * Green channel.
             */
            unsigned char g;

            /**
             * Blue channel.
             */
            unsigned char b;

            /**
             * Alpha channel.
             */
            unsigned char a;
        #elif defined(PNTR_PIXELFORMAT_ARGB)
            /**
             * Blue channel.
             */
            unsigned char b;

            /**
             * Green channel.
             */
            unsigned char g;

            /**
             * Red channel.
             */
            unsigned char r;

            /**
             * Alpha channel.
             */
            unsigned char a;
        #endif
    } rgba;
```
I don't know if it causes a problem or if it's related to your current issue but to me that looks inconsistent.  In the PIXELFORMAT_ARGB case the order in memory would be BGRA but for PIXELFORMAT_RGBA it would be RGBA.  It doesn't matter whether you're LSB or MSB the relative orders are not the same between the two formats.  Am I crazy?  I don't think any of this matters if you pass things directly from PGL to raylib/OpenGL without ever reinterpreting it as your color type or messing with it but the differences between PGL/SDL color formats and pntr might still be an indirect cause, again, gradient notwithstanding.


> Right? It's very strange. I just added a few rectangles at the top using software rendering via pntr to ensure the raylib textures are represented correctly...

Yeah, and the colors are in the correct order even on PGL's triangle which makes me think everything I said above is irrelevant, or at least mostly irrelevant.  But if the colors are in the correct places, then alpha should be too.  And we're back to what on earth could make it darker, and more dark as it's less red.

I don't know but maybe something in this long response will spark an idea on your end.

**Comment by rswinkle** [comment]
Well now I'm embarrassed.  It *is* a PGL problem.  I just wrote the frame out to a png and it is transparent in that gradient.  I probably (hopefully) introduced it back in September/October when I added support for vertex attribute types other than float.  I'll post again once I've tracked it down.

**Comment by rswinkle** [comment]
False alarm.  It was indirectly my fault but not anything to do with PGL proper.  I had a really stupid mistake in ex2.c and you copy pasta'd it.  Here's the diff ... all that searching and it was right in front of me *facepalm*

```c
        glEnableVertexAttribArray(0);
        glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(float)*6, 0);
        glEnableVertexAttribArray(4);
-       glVertexAttribPointer(4, 4, GL_FLOAT, GL_FALSE, sizeof(float)*6, (void*)(sizeof(float)*3));
+       glVertexAttribPointer(4, 3, GL_FLOAT, GL_FALSE, sizeof(float)*6, (void*)(sizeof(float)*3));
 
        // Note, no uniforms used in these shaders so no need to set any
        GLuint myshader = pglCreateProgram(smooth_vs, smooth_fs, 4, smooth, GL_FALSE);
```

Or a slightly more involved change but theoretically slightly faster:

```c
     appData->context = pntr_load_glContext(app->screen);
 
     // Set up the OpenGL state
-       GLenum smooth[4] = { PGL_SMOOTH4 };
+       GLenum smooth[3] = { PGL_SMOOTH3 };
 
        float points_n_colors[] = {
                -0.5, -0.5, 0.0,
@@ -39,10 +39,10 @@ bool Init(pntr_app* app) {
        glEnableVertexAttribArray(0);
        glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(float)*6, 0);
        glEnableVertexAttribArray(4);
-       glVertexAttribPointer(4, 4, GL_FLOAT, GL_FALSE, sizeof(float)*6, (void*)(sizeof(float)*3));
+       glVertexAttribPointer(4, 3, GL_FLOAT, GL_FALSE, sizeof(float)*6, (void*)(sizeof(float)*3));
 
        // Note, no uniforms used in these shaders so no need to set any
-       GLuint myshader = pglCreateProgram(smooth_vs, smooth_fs, 4, smooth, GL_FALSE);
+       GLuint myshader = pglCreateProgram(smooth_vs, smooth_fs, 3, smooth, GL_FALSE);
        glUseProgram(myshader);
 
     return true;
@@ -73,7 +73,8 @@ void smooth_vs(float* vs_output, pgl_vec4* vertex_attribs, Shader_Builtins* buil
 }
 
 void smooth_fs(float* fs_input, Shader_Builtins* builtins, void* uniforms) {
-       builtins->gl_FragColor = ((pgl_vec4*)fs_input)[0];
+       pgl_vec3 c = *(pgl_vec3*)fs_input;
+       builtins->gl_FragColor = make_vec4(c.x, c.y, c.z, 1.0f);
 }
```

I apologize for such a dumb mistake, that's what happens when there's no way to actually see the issue.  Turning on blend mode for the SDL texture would have made the issue obvious from the start so I should probably turn that on when I make changes just to double check before committing.

Let me know if there's anything else you run into (I'll leave this issue open for now).

**Comment by rswinkle** [comment]
Technically the vertex shader should change too, from this:
```c
void smooth_vs(float* vs_output, pgl_vec4* vertex_attribs, Shader_Builtins* builtins, void* uniforms) {
	((pgl_vec4*)vs_output)[0] = vertex_attribs[4]; //color
	builtins->gl_Position = vertex_attribs[0];
}
```
to this:
```c
void smooth_vs(float* vs_output, pgl_vec4* vertex_attribs, Shader_Builtins* builtins, void* uniforms) {
	((pgl_vec3*)vs_output)[0] = *(pgl_vec3*)&vertex_attribs[4]; //color
	builtins->gl_Position = vertex_attribs[0];
}
```
or some other way of not writing the 4th channel to vs_output.  But you'd have to be doing a draw call with PGL_MAX_VERTICES and be on the very last vertex for that extra 4 byte write to actually be out of bounds though.

**Comment by RobLoach** [comment]
Great investigation! That worked well. Would you like me to update the examples?

**Comment by rswinkle** [comment]
It took me two tries (forgot the ex2_std_shaders.c example when I fixed ex2.c) but I got them.  ex2.cpp and ex3.c/cpp actually pass the 1.0 alpha explicitly so there was no issue there.

Unless there's something else you see?  I should probably go through all the demos/tests closely too and make sure I don't make a similar mistake anywhere but I'll do that later.

**Comment by RobLoach** [comment]
As long as the first few examples are good, I'd be happy on closing this. Thanks so much for all the help.

This update will definitely help for when you're considering a raylib example. Raylib will definitely save a bit of code over the SDL examples :wink: 
```c
Image image;
image.width = 640;
image.height = 480;
image.format = PIXELFORMAT_RGBA8888
image.data = bbufpix;
Texture texture = LoadTextureFromImage(image);
UnloadImage(image);
// ...
UpdateTexture(texture, bbufpix);
```

**Comment by rswinkle** [comment]
You're very welcome.  It's like Linus said, users are the best bug testers/finders.

> This update will definitely help for when you're considering a raylib example. Raylib will definitely save a bit of code over the SDL examples 😉

Maybe, but while I see the point of what you're doing, integrating PGL into pntr, a 2D drawing API with multiple backends, including none/software rendering like PGL itself, raylib already has OpenGL built into it.  I can't see why someone would want to use PGL offscreen to generate a texture when they could do the same with OpenGL via Raylib directly.

I've exchanged some messages with Ramon/raysan5 in [the past](https://github.com/raysan5/raylib/discussions/2036) about integrating PGL into raylib/rlgl.h as a software rendering fallback but at the time it didn't make any sense when Raylib was GLFW only.  Now with the 5.0 update and added SDL backend it's possible but that's a time consuming task that should wait till I reach 1.0.

Good luck with the rest of pntr, I'll definitely have to try it sometime.
