### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [rswinkle/PortableGL#20]
👋 while upgrading [sdl2 to 2.30.3](https://github.com/Homebrew/homebrew-core/pull/170559), I ran into some regression test failure with portablegl 0.97.1, and it is reproducible even with a rebuild. And then after I rebuild from the master, the regression tests run well again.

Can you cut a new release to help refresh the homebrew formula? Thanks!

cc @rswinkle

**Comment by rswinkle** [comment]
Thanks for the heads up.

I have been planning to do this for months as soon as I finish some things I wanted to get into 0.98.0 and some other background work but at this point it's been over a year since 0.97 so now is as good a time as any and I'll just move most of that to the next tagged release.

I'll try to get it out this weekend at the latest.

**Comment by chenrui333** [comment]
wonderful, thanks @rswinkle!

**Comment by rswinkle** [comment]
Let me know if there are any problems with 0.98.0 and if not I'll close this.
