### ISSUE TITLE
(Question) Mesa3D contributions

### ISSUE THREAD

**Issue by hardBSDk** [rswinkle/PortableGL#23]
Do you contributed to Mesa3D?

**Comment by rswinkle** [comment]
I have not.  I could get into it if I really wanted to but I have enough of my own projects to work on.  Even ignoring all my other projects, PortableGL would be enough to keep me busy full time for years, if it paid the bills.  I have some vague future plans to help on that front but for now, since it's just a "for fun" project I work on it when I can.

Why do you ask?
